### ISSUE TITLE
I am not sure is this an issue but it's make me feel discomfort because it's too Asymmetrical

### ISSUE THREAD

**Issue by Ichi1234** [KhunakornP/A-plus-management#169]
![image](https://github.com/user-attachments/assets/cb13660d-5060-41f9-a2da-8b0e2e68bb6a)

**Comment by Ichi1234** [comment]
Do you intend to position the button like this? I think it's pretty weird. It should be in the middle or something.

![image](https://github.com/user-attachments/assets/ade5dea4-c247-4885-8649-feb9463c66db)

**Comment by KhunakornP** [comment]
I wouldn't say that the positions of the buttons makes the UI unreasonably hard to navigate so I'll not be marking this as an Issue. Though I'll be sure to discuss this suggestion with the team the next meeting.
