### ISSUE TITLE
Tasks API is return all of the data not only the one that own by current user

### ISSUE THREAD

**Issue by OmegaOoh** [KhunakornP/A-plus-management#171]
## Description
I can see every task by anyone
## To reproduce
visit https://a-plus-management.onrender.com/api/tasks/ and see the response JSON

![image](https://github.com/user-attachments/assets/bcfda7b5-d6f6-4ab5-afbe-63fddc5a620d)

**Comment by KhunakornP** [comment]
Hmm yes, It would appear my backend has no authentication check. Will look into it
