### ISSUE TITLE
Score weight field should be disabled for selected major in A-level Calculator

### ISSUE THREAD

**Issue by PHIMNADA024** [KhunakornP/A-plus-management#172]
## The Problem
In the A-level Calculator, users are currently allowed to modify the score weight even after selecting a major. However, this feature seems unnecessary, as each major already has predefined score weights. Disabling the score weight field after selecting a major would ensure consistency and prevent user confusion.

## How to reproduce the problem
1. Go to the A-level Calculator.
2. Fill in the score fields.
3. Select a major.
4. Observe that the score weight field is still editable.

## Screenshot
![image](https://github.com/user-attachments/assets/c7baaca1-35e1-4e82-8f23-8df3dbd1d306)

**Comment by KhunakornP** [comment]
The user are actually supposed to be able to modify the score weights after selecting a major. This is a deliberate feature incase the data is for whatever reason outdated. Also, in if the user modifies the score weights directly they would know why the score would differ from normal computation. After consulting with the team I will not be marking this as an issue please mark this issue again if you have a stronger argument.

**Comment by KhunakornP** [comment]
Actually, no need to create a new issue, you can post your reasoning here and I'll re open the Issue if it is valid.
