### ISSUE TITLE
Unnecessary A-level selection question for parents

### ISSUE THREAD

**Issue by PHIMNADA024** [KhunakornP/A-plus-management#173]
# The problem
In the parent section, users are prompted to choose whether they are taking A-levels. This question is irrelevant for parents, as they are not the ones taking the exams. Removing this prompt would improve the user experience by eliminating unnecessary steps.

# How to reproduce the problem
1. Log in and select the parent role.
2. Navigate to the A-level selection page.
3. Observe that parents are asked to indicate whether they are taking A-levels.

**Comment by KhunakornP** [comment]
Due to many of the members being asleep I will be marking this as needs clarification for now. I will update this once the team reaches a consensus. Though I would to ask if clicking 2 more buttons this that much of a hassle for setting up your account once.

**Comment by PHIMNADA024** [comment]
From a user experience perspective, it feels odd to ask parents if they are taking A-levels.

**Comment by KhunakornP** [comment]
Technically they can though, ทปอ Doesn't limit your age nor education so long as you have at least ม.6 equivalent education or higher

**Comment by PHIMNADA024** [comment]
I understand that students who have completed secondary school may have taken A-levels. However, it doesn't make sense to ask parents if they are taking A-levels, as they are not the ones sitting the exams. This question is unnecessary and could lead to confusion, as it serves no practical purpose for parents using the system.

**Comment by KhunakornP** [comment]
You seem to not have understood what I said. It is perfectly possible for a Parent, Regardless of their age and education status to sit the A-levels so long as they have the pre-requisite education.

**Comment by KhunakornP** [comment]
I understand that from a technical point of view the answer to the question as a parent has no consequence whatsoever. However I disagree that it leads to confusion. It is simply asking if you are taking the A-levels, It is not implying anything other than that.

**Comment by KhunakornP** [comment]
As for the reason why choosing this choice matters for a student, the calculator itself is pretty heavy computation wise and if possible I do not want children to mash inputs into the calculator.

**Comment by PHIMNADA024** [comment]
I don't understand why calculating A-level scores would require heavy computation. Additionally, for the parent or student role, I don’t see the point of asking if someone has taken A-levels. From a user perspective, it doesn’t make sense to include this choice. It’s not just about adding an extra step during sign-up—parents are typically the father or mother of the student, not adults who need to take A-levels themselves. This question seems unnecessary for parents. Of course, if you don’t agree, that’s fine—it’s just my opinion as a user, and you’re not obligated to follow my suggestion.

**Comment by BioB3** [comment]
And why can't parents take A-levels, are you implying that parents can't enroll in universities that are in myTCAS system?

**Comment by KhunakornP** [comment]
> I don't understand why calculating A-level scores would require heavy computation. Additionally, for the parent or student role, I don’t see the point of asking if someone has taken A-levels. From a user perspective, it doesn’t make sense to include this choice. It’s not just about adding an extra step during sign-up—parents are typically the father or mother of the student, not adults who need to take A-levels themselves. This question seems unnecessary for parents. Of course, if you don’t agree, that’s fine—it’s just my opinion as a user, and you’re not obligated to follow my suggestion.

You need not understand why the scores would require computation, We know because we are the ones who wrote the code. Also, are you claiming that parents cannot take the A-levels if they have children? What about 32 year old adults who have children but failed to get into university? Due to the teams consensus that this is not an Issue I will be marking this as not a defect since this is more of a suggestion rather than an Issue. Feel free to open another Issue if you still think that this is worthy of an issue and provide a stronger argument rather than "As a user I don't like this".
