### ISSUE TITLE
Not Notify when enter wrong GPAX

### ISSUE THREAD

**Issue by JaofourthsOhappy** [KhunakornP/A-plus-management#175]
I enter wrong GPAX  it should notify error same TGAT & TPAT,A-Level

<img width="1728" alt="Screenshot 2567-11-25 at 12 34 24" src="https://github.com/user-attachments/assets/2164341c-1bbe-40b4-9d7c-892b8e827fb8">

**Comment by KhunakornP** [comment]
I will wait patiently for 24 hours, If you do not specify what exactly is wrong I will be closing this issue.

**Comment by JaofourthsOhappy** [comment]
In GPAX i enter 3.999  it should notify that can enter only 2 decimal

**Comment by KhunakornP** [comment]
> In GPAX i enter 3.999 it should notify that can enter only 2 decimal

What about the other issues, Also you can have 3.875 GPAX.

**Comment by KhunakornP** [comment]
> I enter wrong GPAX it should notify error same TGAT & TPAT,A-Level

You said the other scores should notify errors like GPAX could you please elaborate on that.

**Comment by KhunakornP** [comment]
Closing this, due to inactivity
