### ISSUE TITLE
Can create task board for other users

### ISSUE THREAD

**Issue by Pawat-Sarnchawanakit** [KhunakornP/A-plus-management#176]
By changing the user field in the JSON in the request to /api/taskboards/ as show below and send the request:
![image](https://github.com/user-attachments/assets/35b23642-1bd8-4e16-9bc9-4c39dac1e055)

I was able to create task board for other users.

**Comment by KhunakornP** [comment]
Yes this is indeed an Issue with the REST API. I'll look into it.

**Comment by KhunakornP** [comment]
For future reference I will not be accepting other Issues with the REST API as #171 and this Issue has confirmed that the entire endpoint is compromised.

**Comment by KhunakornP** [comment]
Also I see you've taken the liberty of creating 2000 task boards. Very impressive.
