### ISSUE TITLE
Excessively large text in taskboard name incorrectly handled by the application.

### ISSUE THREAD

**Issue by PHIMNADA024** [KhunakornP/A-plus-management#177]
##**Bug or Defect**
Excessively large text in taskboard name incorrectly handled by the application.
I tried this given input, and I cannot create the taskboard as the application gave the error of `Taskboard name cannot be blanked.`

``` https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus-management.onrender.com/manager/taskboard/https://a-plus ```
more lines omitted...

## **How To Reproduce**
1. Go to  'Taskboard' page
2. Click on 'Create a taskboard'
3. In the taskboard name field, input an extremely long text string (e.g., 1,000 characters or more)
4. Click on 'Create' button
5. The system incorrectly displays an error message stating that the field is blank, and the taskboard cannot be created.

**Expected behavior**
The taskboard name should have a character limit. The error message should accurately indicate the issue (e.g., "Taskboard name exceeds the character limit").

**Screenshots**
![image](https://github.com/user-attachments/assets/aeb083b0-f4bc-4b27-8814-1f9474d425e6)

**Desktop (please complete the following information):**
 - OS: [Window11
 - Browser: Chrome
 - Version: 23

**Comment by KhunakornP** [comment]
Sure!

**Comment by KhunakornP** [comment]
Btw this is not a `Functionality` Error the limit is being enforced. This is an `Appearance` Defect. I have taken the liberty of updating the bug bounty tracker. Feel free to debate me on why you think this is a Functionality error.

**Comment by KhunakornP** [comment]
Apologies, I have revised the criteria for a `Functionality` issue and yes I agree this would classify as one.

**Comment by PHIMNADA024** [comment]
Some lines of code have been omitted. Sorry about that.
