### ISSUE TITLE
Defects in Bug Report Template

### ISSUE THREAD

**Issue by fatalaijon** [KhunakornP/A-plus-management#182]
##**Bug or Defect**

This Bug Report template contains a Markdown Error and some misuse of Markdown.
The Markdown Error is in the section title for this section! 
- needs a space after the `##` (otherwise Markdown does not recognize it as section header)
- don't use `**` for bold text in section titles.  The Markdown formatter will apply font weighting itself (it will be bold in this case).

There are 2 misuses of Markdown

1. Using bold inside a section title like this: `## **How To Reproduce**`. Should be `## How To Reproduce`.
2. Some sections use `**` instead of a section header line `##`.  The text entered on the following line will be displayed on same line as the "header" text.  If you consistently use `##` it would format better & look consistent.

## **How To Reproduce**
1. Create a Bug Report
2. Github Issue editor window shows this:

```markdown
##**Bug or Defect**
...
## **How To Reproduce**
...
**Expected behavior**
...
**Screenshots**
...
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
...
```

**Expected behavior**

Template should contain formatting like this:
```
## Description of Defect
...
## How To Reproduce
...
## Expected behavior
...
## Screenshots
...
## Desktop (please describe desktop environment)
 - OS: [e.g. iOS]
...

**Comment by KhunakornP** [comment]
Fixed in commit: https://github.com/KhunakornP/A-plus-management/commit/2b0ed9e858086cf13fc86b323b5ef88688dc46d8, We've also added new templates for Defects and suggestions, if you'd like please check them out!
