### ISSUE TITLE
[Defect]: missing steps in the instructions of installation

### ISSUE THREAD

**Issue by Pat-7-626** [KhunakornP/A-plus-management#185]
## Which feature is related to your problem?
Installation part:

7. import data

```
#TODO update this when the data fixture is finalized
```

Defect: Installation instructions don’t work. You tried to install and run it locally using installation instructions in project’s Github repository, but they don’t work. ```This includes missing steps in the instructions.```

## Describe the solution you'd like
Add the real one so people don't have to find the name themselves OR delete this if import data unnecessary for this project so it won't cause confusion.

**Comment by KhunakornP** [comment]
Ah, I was wondering if someone would notice that. Thank you for reporting it. I will resolve this alongside the planned changes to the readme
