### ISSUE TITLE
Write logic to handle dragging and dropping tasks into boxes

### ISSUE THREAD

**Issue by KhunakornP** [KhunakornP/A-plus-management#21]
Write logic using bootstrap or html to handle dragging tasks between status boxes.
Whenever a tasks is dragged to a box update the task's status to match the current box as well.

**Comment by Jangsoodlor** [comment]
I think this task also requires modifying the `views.py` as well.

**Comment by KhunakornP** [comment]
Yeah now that I think about it to whomever is going to do this task you might also want to modify or create a view to update the task status as well
