### ISSUE TITLE
Write function(s) to convert the burndown chart data to a graph object

### ISSUE THREAD

**Issue by Jangsoodlor** [KhunakornP/A-plus-management#57]
Write functions to convert the data prepared in #49 to be a graph object. In this case, `matplotlib.Figure`

**Comment by KhunakornP** [comment]
> Write functions to convert the data prepared in [#49](https://github.com/KhunakornP/A-plus-management/issues/49) to be a graph object. In this case, `matplotlib.Figure`

Extending this issue to Iteration 3 since we are swapping to [chart js](https://www.chartjs.org/)
